name: activity_monitor
description: A new Flutter project.


publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter  
  cupertino_icons: ^1.0.2
 
  #StateManagements
  hooks_riverpod: ^2.3.7
  rxdart: ^0.27.7

  #Networks
  connectivity_plus: ^4.0.2
  http: ^1.1.0

  #Local Storage
  flutter_secure_storage: ^8.0.0
  shared_preferences: ^2.2.0
  #Widgets
  another_flushbar: ^1.12.30
  image_picker: ^1.0.2
  #Features
  google_sign_in: ^6.1.4
  fpdart: ^1.1.0
  flutter_hooks: ^0.20.0
  #google api
  googleapis: ^11.4.0
  googleapis_auth: ^1.4.1
  url_launcher: ^6.1.12
  

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/json/language/

  
  
  
  

  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
